### PR TITLE
Cancel

### PR DESCRIPTION
**Pull request by carlosemv**
Defining a "/cancel" command for canceling existing (whether initiated or not) games. Please let me know what you think.

P.S. New strings are defined only for english and pt-br, so there would still need to be translations to french and esperanto.

### CODE REVIEW

**Comment by bpeel** [comment]
Thanks for the patch. It looks good, but I wonder if we should limit the command to people who are in the game. Otherwise it seems like it would be ripe for trolling where random people come in and cancel a game just before the end.

I was also thinking that maybe it would be nice to have a method for the other players to confirm the cancellation. Something like if someone cancels a game then it waits for 30 seconds with a question allowing anyone to cancel the cancellation. I’m not sure if that’s really necessary though.

**Comment by carlosemv** [comment]
You're definitely right about only people in the game being able to cancel it, I didn't even think about that.

Having other players confirm it, maybe not necessary, but probably good to have it anyway.

I'll look into implementing these ASAP, thanks for the quick feedback!

**Comment by carlosemv** [comment]
I've done the first part, but I'm stumped on the second.

I've been looking into how I could make it work like a challenge on coup (If any player 'challenges' the game is not canceled, and there's a timeout to challenge), but I'm still not sure...

Would I need to keep an instance of something like coup's challenge_data struct? Inside the pcx_bot or game struct perhaps?

**Comment by bpeel** [comment]
I think there would only ever be one cancellation in-flight per game, so I guess you could just put a `pcx_main_context_source` for the timeout directly in the `struct game`.

On the other hand, I’m still not really sure whether the confirmation is needed, so if you agree I’m happy to just merge your branch as it is.

**Comment by carlosemv** [comment]
You're right, I've been playing this version with some friends and the cancel function is already pretty useful as is 👍

**Comment by bpeel** [comment]
I’ve merged the branch. Thanks for working on it.

**Pull request closed without merging**
